---
- name: Run acro-add-website
  shell: >
     export TERM=xterm-256color; /usr/bin/timeout 30s /bin/bash /usr/local/sbin/acro-add-website.sh --account {{ linux_owner }} --project {{ project }} --fqdn {{ nginx_primal_name }} --webroot {{ web_root_dir_name }} --php-version {{ php_version }} --responsible-person {{ responsible_person }}
  args:
    creates: /home/{{ linux_owner }}/.acro-add-website/{{ project }}

- name: Try and expand the primal name's Certificate to include nginx aliases and canonical name. If DNS is pointing at the machine for these names, the command will work.
  shell:  >
    /usr/local/bin/certbot-auto --no-self-upgrade certonly --non-interactive --webroot --agree-tos -w /var/www/letsencrypt  --email webmaster@acromedia.com --cert-name {{ nginx_primal_name }} --keep -d "{{ nginx_canonical_name }},{{ nginx_aliases |join(',') }},{{ nginx_primal_name }}"
  when:
    letsencrypt_canonical == true
  register: letsencrypt_result
  ignore_errors: true

- name: Put LE enabled nginx config in place for sites that have a working LE cert
  template:
    src: "{{ role_path }}/templates/{{ nginx_canonical_template }}"
    dest: /etc/nginx/sites-available/{{ nginx_primal_name }}
    backup: true
  when: letsencrypt_result is defined
    and letsencrypt_result.rc is defined
    and letsencrypt_result.rc == 0
  notify:
    - safe reload nginx
