---
- include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Make sure we have an nginx_listeners array
  assert:
    that:
      - (nginx_listeners | length) > 0
      - nginx_listeners is not string
      - nginx_listeners is iterable
    fail_msg: "The 'nginx_canonical_name', 'nginx_primal_name', 'nginx_aliases', 'deploy_env', and 'ssl' variables have been replaced by the much more flexible 'nginx_listeners' and 'letsencrypt_certificates' definitions. You need to convert your playbook's variables before continuing. See the role's README.md for details."

- name: debug nginx_listeners array
  debug:
    var: nginx_listeners
    verbosity: 1

- name: Validate 'web_application' variable value
  assert:
    that:
      - web_application == 'php'
          or web_application == 'drupal8'
          or web_application == 'drupal7'
          or web_application == 'drupal6'
          or web_application == 'drupal5'
          or web_application == 'drupal4'
          or web_application == 'proxy_pass'
          or web_application == 'redirect'
          or web_application == 'static'
          or web_application == 'wordpress'
          or web_application == 'mediawiki'
          or web_application == 'moodle'
    fail_msg: "ERROR: Value for web_application is not supported: {{ web_application }}"

- name: Make sure linux_owner is not the same as php_service_user
  assert:
    that:
      - linux_owner != php_service_user
    fail_msg: "ERROR: The PHP user (php_service_user) cannot be the same account as the web account owner (linux_owner).\n
      If they are, the account will be marked as a 'service' account, SSH will not work for it, and you will\n
      not be able create a working CI deploy job."

- name: Warn about letting the role use the default value for php_fpm_newrelic_appname
  assert:
    that: php_fpm_newrelic_appname != (linux_owner + '/' + project)
    fail_msg: If using New Relic, be sure to set a meaningful app name. A good format to use is "yourdomain.com - env descriptor". Set the value to anything other than the default to disable this message.
  ignore_errors: true

- name: See if a site has already been created with AAW
  stat:
    path: /home/{{ linux_owner }}/.acro-add-website/{{ project }}
  register: aaw_hints_result

- name: Prevent AAW from strpping characters out of account or project file names.
  fail:
    msg: The combination of linunx_owner + project name cannot exceed 16 characters.
  when: "(linux_owner != project and (linux_owner|length + project|length) > 16)
    and (aaw_hints_result is defined and aaw_hints_result.stat.exists == false)
    "

- name: Prevent AAW from clipping php service user account names
  fail:
    msg: "The system can't reliably auto-generate a php service user name if the length of 'linunx_owner' exceeds 12 characters. You will need to manually specify the value for 'php_service_user' in your role variables (e.g. 'php_service_user: foo-srv')."
  when: "(php_service_user == '')
    and (linux_owner|length > 12)
    and (aaw_hints_result is defined and aaw_hints_result.stat.exists == false)
    "

# We need to set facts here using internal names, as opposed to the ones we told the role consumer about, because:
# 1: This role is meant to be used multiple times in the same playbook,
# 2: Ansible is basically scopeless; everything is global
# 3: Once we set a fact in a role, it overrides the role's "defaults" the next time the role is used.
# 4: We need to provide a way for the consumer to override defaults, without imposing variable bleed across multiple uses
- name: (Re)set some runtime variables for the role's internal use
  set_fact:
    skip_ssl_flag: ''
    skip_mysql_flag: ''
    rds_flag: ''
    force_flag: ''
    service_account_flag: ''
    x__php_service_user: ''
    x__fpm_pool_filename: ''
    env_mysql_db_name: ''
    env_mysql_db_user: ''
    env_mysql_db_pass: ''

- set_fact:
    skip_ssl_flag: '--skip-ssl'
  # when: ssl == 'none'
  #   or (ssl == 'manual' and deploy_env == 'production')

- set_fact:
    rds_flag: '--rds'
  when: "rds == true"

- set_fact:
    x__fpm_pool_filename: "{{ project }}.conf"
  when: "fpm_pool_filename == ''
    and project == linux_owner"

- set_fact:
    x__fpm_pool_filename: "{{ linux_owner }}-{{ project }}.conf"
  when: "fpm_pool_filename == ''
    and project != linux_owner"

- set_fact:
    x__fpm_pool_filename: "{{ fpm_pool_filename }}"
  when: "x__fpm_pool_filename == ''
    and fpm_pool_filename != '' "

- set_fact:
    x__php_service_user: "{{ project }}-srv"
  when: "php_service_user == ''
    and project == linux_owner"

- set_fact:
    x__php_service_user: "{{ linux_owner }}-{{ project }}-srv"
  when: "php_service_user == ''
    and project != linux_owner"

- set_fact:
    x__php_service_user: "{{ php_service_user }}"
  when: "php_service_user != ''"

- set_fact:
    service_account_flag: '--service-account {{ x__php_service_user }}'
  when: "x__php_service_user != ''"

- set_fact:
    force_flag: '--force'
  when: "force == true"

- set_fact:
    skip_mysql_flag: '--skip-mysql'
  when: skip_mysql == true

- set_fact:
    env_mysql_db_name: 'DBNAME="{{ mysql_db_name }}"'
  when: (mysql_db_name|trim) != ''

- set_fact:
    env_mysql_db_user: 'DBUSER="{{ mysql_db_user }}"'
  when: (mysql_db_user|trim) != ''

- set_fact:
    env_mysql_db_pass: 'DBPASS="{{ mysql_db_pass }}"'
  when: (mysql_db_pass|trim) != ''

- name: Make sure dhparams.pem has a place to live.
  file:
    state: directory
    dest: "{{ dir.dest }}"
    mode: "{{ dir.mode }}"
  loop:
    - dest: /usr/local/ssl
      mode: '0755'
    - dest: /usr/local/ssl/private
      mode: '2750'
  loop_control:
    loop_var: dir

- name: Make sure Diffie Hellman parameters file has been initialized for SSL-enabled sites (can take several minutes on slow systems)
  shell: umask 077 && openssl dhparam -out /usr/local/ssl/private/dhparams.pem 2048
  args:
    creates: /usr/local/ssl/private/dhparams.pem

- name: Make sure the Acme Challenge include file exists, even if LetsEncrypt is not installed on the system. Otherwise we will end up with nginx fatal config errors.
  copy:
    dest: /etc/nginx/includes/letsencrypt-acme-challenge.conf
    content: ''
    force: false
    mode: 0644
    owner: root
    group: root

- name: Compose AAW command line
  set_fact:
    _aaw_cli: >
       export TERM=xterm-256color {{ env_mysql_db_name }} {{ env_mysql_db_user }} {{ env_mysql_db_pass }};
       /usr/bin/timeout {{ letsencrypt_cert_registration_timeout }}s
       /bin/bash /usr/local/sbin/acro-add-website.sh
       --account {{ linux_owner }}
       --project {{ project }}
       --fqdn {{ aaw_default_fqdn }}
       --webroot {{ web_root_dir_name }}
       --php-version {{ php_version }}
       --responsible-person {{ responsible_person }}
       --mysql-allow-from {{ mysql_allow_from }}
       --mysql-host-address {{ mysql_host_address }}
       {{ skip_ssl_flag }}
       {{ rds_flag }}
       {{ service_account_flag }}
       {{ force_flag }}
       {{ skip_mysql_flag }}

- name: Debug _aaw_cli
  debug:
    var: _aaw_cli
    verbosity: 1

- name: Run AAW command line  #, waiting up to {{ letsencrypt_cert_registration_timeout }} seconds for letsencrypt cert registration
  shell: "{{ _aaw_cli }}"
  args:
    creates: /home/{{ linux_owner }}/.acro-add-website/{{ project }}
  register: aaw_result

- name: debug aaw_result
  debug:
    var: aaw_result
    verbosity: 1

- name: Register or expand letsencrypt certificate(s). If DNS is pointing at the machine for all names, and the firewall is open to port 80, the command should succeed.
  script:  scripts/certbot-wrapper
  args:
    executable: /bin/bash
  environment:
    INVENTORY_HOSTNAME: "{{ inventory_hostname }}"
    CERT_NAME: "{{ item.name }}"
    NGINX_PRIMAL_NAME: "{{ item.name }}"
    DOMAINS_LIST: "{{ item.domains | join(',') }}"
    LE_EXPIRY_EMAIL: "{{ letsencrypt_expiry_email }}"
  with_items: "{{ letsencrypt_certificates }}"
  register: letsencrypt_result
#  ignore_errors: true
  notify: arvh safe reload nginx

- name: debug letsencrypt_result
  debug:
    var: letsencrypt_result
    verbosity: 1

- name: Configure arbitrary NGINX "http" context customizations
  template:
    src: "{{ role_path }}/templates/etc/nginx/conf.d/ACCOUNT-PROJECT.conf.j2"
    dest: "{{ vhost_path_to_nginx_conf_d_inline_custom }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: arvh safe reload nginx

- name: Upload arbitrary NGINX "server" context customizations from the playbook through the role to the remote host
  template:
    src: "{{ nginx_include_custom }}"
    dest: "{{ nginx_include_custom_dest }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: arvh safe reload nginx
  when: nginx_include_custom != ''

- name: Configure nginx rate limit memory zone to protect PHP FPM on {{ linux_owner }}/{{ project }}
  template:
    src: "{{ role_path }}/templates/etc/nginx/conf.d/limit_req_zone.ACCOUNT-PROJECT.conf.j2"
    dest: "{{ nginx_limit_req_zone_file }}"
    backup: true
    owner: root
    group: root
    mode: 0644
  notify:
    - arvh safe restart nginx
  when: php_version != 'none'

- name: Update PHP FPM nginx include for {{ linux_owner }}/{{ project }}
  template:
    src: "{{ role_path }}/templates/etc/nginx/includes/ACCOUNT-PROJECT.php-fpm.conf.j2"
    dest: "{{ path_to_nginx_php_fpm_include }}"
    backup: true
  notify:
    - arvh safe reload nginx
  when: php_version != 'none'

- name: Update nginx core conf include for {{ linux_owner }}/{{ project }}
  template:
    src: "{{ role_path }}/templates/etc/nginx/includes/ACCOUNT-PROJECT.core.conf.j2"
    dest: "/etc/nginx/includes/{{ linux_owner }}-{{ project }}.core.conf"
    backup: true
  notify:
    - arvh safe reload nginx

- debug:
    var: nginx_location_extras
    verbosity: 1

- name: Update nginx virtual host configuration for {{ linux_owner }}/{{ project }}
  template:
    src: "{{ role_path }}/templates/etc/nginx/sites-available/ACCOUNT-PROJECT.conf.j2"
    dest: "{{ nginx_vhost_conf_dir }}/{{ linux_owner }}-{{ project }}.conf"
    backup: true
  notify:
    - arvh safe reload nginx

- name: Enable (symlink) nginx virtual host configuration for {{ linux_owner }}/{{ project }}
  file:
    src: "/etc/nginx/sites-available/{{ linux_owner }}-{{ project }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ linux_owner }}-{{ project }}.conf"
    state: link
  when: ansible_os_family == 'Debian'
    and not ansible_check_mode
  notify:
    - arvh safe reload nginx

- name: Remove vhost files that used the old naming convention
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - /etc/nginx/sites-available/{{ nginx_primal_name }}
    - /etc/nginx/sites-enabled/{{ nginx_primal_name }}
  when: ansible_os_family == 'Debian'
    and nginx_primal_name is defined
    and (nginx_primal_name | length) > 0
  notify:
    - arvh safe reload nginx

- name: Remove old duplicate {{ php_fpm_pool_dir }}/{{ linux_owner }}-{{ project }}.conf
  file:
    path: "{{ php_fpm_pool_dir }}/{{ linux_owner }}-{{ project }}.conf"
    state: absent
  when: linux_owner == project
  notify:
    - arvh restart php-fpm

# @TODO: Add logrotate config for this file.
- name: Precipitate the PHP FPM slowlog file
  when: arvh_php_fpm_slowlog_enabled
  copy:
    dest: "{{ arvh_php_fpm_slowlog_path }}"
    content: ''
    force: false
    mode: '0640'
    owner: "{{ x__php_service_user }}"
    group: "{{ arvh_php_fpm_slowlog_group }}"
  notify:
    - arvh restart php-fpm

- name: Update PHP {{ php_version }} FPM pool for {{ linux_owner }}/{{ project }}
  template:
    src: "{{ role_path }}/templates/etc/php/VERSION/fpm/pool.d/ACCOUNT-PROJECT.conf.j2"
    dest: "{{ php_fpm_pool_dir }}/{{ x__fpm_pool_filename }}"
    backup: true
  notify:
    - arvh restart php-fpm
  when: php_version != 'none'

- name: Enumerate /etc/php/VERSION/fpm/pool.d directories that are not "{{ php_version }}", used by the 'remove' task below)
  shell: >
    /usr/bin/find /etc/php -maxdepth 3 -type d -path '/etc/php/*/fpm/pool.d' | /usr/bin/cut -d'/' -f 4 | (grep -v "{{ php_version }}" || true)
  register: cmdresult_enumerate_php_version_numbers
  changed_when: false
  when: php_version != 'none'
    and ansible_os_family == 'Debian'

- name: Remove all FPM pools that are not PHP {{ php_version }} for {{ linux_owner }}/{{ project }} - 1 of 2
  file:
    path: /etc/php/{{ item }}/fpm/pool.d/{{ linux_owner }}-{{ project }}.conf
    state: absent
  with_items:
    - "{{ cmdresult_enumerate_php_version_numbers.stdout_lines|default([]) }}"
  notify:
    - arvh restart php-fpm
  when: php_version != 'none'
    and ansible_os_family == 'Debian'

- name: Remove all FPM pools that are not PHP {{ php_version }} for {{ linux_owner }}/{{ project }} - 2 of 2
  file:
    path: /etc/php/{{ item }}/fpm/pool.d/{{ project }}.conf
    state: absent
  with_items:
    - "{{ cmdresult_enumerate_php_version_numbers.stdout_lines|default([]) }}"
  notify:
    - arvh restart php-fpm
  when: linux_owner == project
    and php_version != 'none'
    and ansible_os_family == 'Debian'

- name: Install dependency for htpasswd operations (Debian)
  apt:
    name:
      - python3-passlib
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install dependency for htpasswd operations (EL 7)
  yum:
    name:
      - python-passlib
    state: present
    update_cache: true
  when: ansible_os_family == 'RedHat'
    and ansible_distribution_major_version == '7'

- name: Install dependency for htpasswd operations (EL 8)
  yum:
    name:
      - python3-passlib
    state: present
    update_cache: true
  when: ansible_os_family == 'RedHat'
    and ansible_distribution_major_version == '8'

- name: Create htpasswd file for {{ linux_owner }}-{{ project }}
  htpasswd:
    path: "{{ path_to_htpasswd_file }}"
    name: "{{ http_auth_username }}"
    password: "{{ http_auth_password }}"
    owner: root
    group: "{{ nginx_process_owner }}"
    mode: 0640
  when: http_auth_username != ''
    and http_auth_password != ''
  ignore_errors: "{{ ansible_check_mode }}"   # This task doesn't always survive check mode.
  notify:
    - arvh safe reload nginx

- name: Warn if letsencrypt_expiry_email is not set, but don't stop the play
  assert:
    that: letsencrypt_expiry_email != ''
    fail_msg: There is no value for letsencrypt_expiry_email. This is not a strict requirement, but it's highly recommended that someone be able to receive expiry notifications in case of unexpected renewal failures.
  when: letsencrypt_certificates is not string
    and letsencrypt_certificates is iterable
    and (letsencrypt_certificates | length > 0)
  ignore_errors: true
