---
# ---------------------------------
# acromedia.postfix
# ---------------------------------
default_mail_recipient: nobody@example.com
postfix_inet_interfaces: 127.0.0.1

# ---------------------------------
# acromedia.nginx
# ---------------------------------
nginx_robots_policy: production

# ---------------------------------
# acromedia.virtual-host
# ---------------------------------
linux_owner: bigcorp
project: bigcorp
nginx_server_name: www.bigcorp.com
nginx_listeners:
  - server_name: "{{ nginx_server_name }}"
    port: 80
php_version: none
web_root_dir_name: wwwroot
web_application: static
skip_mysql: true
require_http_auth: true
http_auth_username: 'test'
http_auth_password: 'test'
