---
# ---------------------------------
# acromedia.postfix
# ---------------------------------
default_mail_recipient: nobody@example.com
postfix_inet_interfaces: 127.0.0.1

# ---------------------------------
# acromedia.nginx
# ---------------------------------
nginx_robots_policy: production

# ---------------------------------
# acromedia.php
# ---------------------------------
php_default_version: 8.1
php_use_legacy_module_lists: false
php_versions:
  - 7.4
  - 8.0
  - 8.1

# ---------------------------------
# acromedia.virtual-host
# ---------------------------------
linux_owner: bigcorp
project: bigcorp
nginx_server_name: www.bigcorp.com
nginx_listeners:
  - server_name: "{{ nginx_server_name }}"
    port: 80
php_version: "{{ php_default_version }}"
web_root_dir_name: wwwroot
web_application: php
skip_mysql: true
require_http_auth: true
http_auth_username: 'test'
http_auth_password: 'test'
