---
# ---------------------------------
# acromedia.postfix
# ---------------------------------
default_mail_recipient: nobody@example.com
postfix_inet_interfaces: 127.0.0.1

# ---------------------------------
# acromedia.nginx
# ---------------------------------
nginx_robots_policy: production

# ---------------------------------
# acromedia.virtual-host
# ---------------------------------
linux_owner: bigcorp
project: bigcorp
nginx_listeners:
  - server_name: staging.bigcorp.com
    port: 80
  - server_name: bigcorp.com
    redirect_to: https://www.bigcorp.com
    redirect_permanent: true
  - server_name: www.bigcorp.com
    port: 80
php_version: none
web_root_dir_name: wwwroot
web_application: static
skip_mysql: true
