---
# Our handler name was colliding with other handlers in the parent playbook... rename it here to prevent weird behaviours.
- name: arvh safe reload nginx
  become: true
  shell: "/usr/sbin/nginx -t && {{ path_to_service_binary }} nginx reload"

- name: arvh safe restart nginx
  become: true
  shell: "/usr/sbin/nginx -t && {{ path_to_service_binary }} nginx restart"

- name: restart php-fpm RedHat
  listen: "arvh restart php-fpm"
  service:
    name: php-fpm
    state: restarted
  when: ansible_os_family == 'RedHat'

- name: restart all php-fpm services Debian
  listen: "arvh restart php-fpm"
  shell: >
    set -eu -o pipefail;
    for SRV in $(dpkg --list | grep php | grep fpm | grep '^ii' | awk '{print $2}'); do
      (set -x && systemctl restart $SRV);
    done
  args:
    executable: /bin/bash
  when: ansible_os_family == 'Debian'
