---
# Our handler name was colliding with other handlers in the parent playbook... rename it here to prevent weird behaviours.
- name: arvh safe reload nginx
  become: true
  shell: "/usr/sbin/nginx -t && {{ path_to_service_binary }} nginx reload"

- name: arvh safe restart nginx
  become: true
  shell: "/usr/sbin/nginx -t && {{ path_to_service_binary }} nginx restart"

- name: restart php5-fpm
  service:
    name: php5-fpm
    state: restarted

- name: restart php5.6-fpm
  service:
    name: php5.6-fpm
    state: restarted

- name: restart php7.0-fpm
  service:
    name: php7.0-fpm
    state: restarted

- name: restart php7.1-fpm
  service:
    name: php7.1-fpm
    state: restarted

- name: restart php7.2-fpm
  service:
    name: php7.2-fpm
    state: restarted

- name: restart php7.3-fpm
  service:
    name: php7.3-fpm
    state: restarted

- name: restart php7.4-fpm
  service:
    name: php7.4-fpm
    state: restarted

- name: restart php8.0-fpm
  service:
    name: php8.0-fpm
    state: restarted

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
