---
- name: safe reload nginx
  become: true
  shell: "test -x /usr/sbin/nginx && /usr/sbin/nginx -tt && test -x /usr/sbin/service && /usr/sbin/service nginx reload"

- name: restart php5-fpm
  service:
    name: php5-fpm
    state: restarted

- name: restart php5.6-fpm
  service:
    name: php5.6-fpm
    state: restarted

- name: restart php7.0-fpm
  service:
    name: php7.0-fpm
    state: restarted

- name: restart php7.1-fpm
  service:
    name: php7.1-fpm
    state: restarted

- name: restart php7.2-fpm
  service:
    name: php7.2-fpm
    state: restarted

- name: restart php7.3-fpm
  service:
    name: php7.3-fpm
    state: restarted

- name: restart php7.4-fpm
  service:
    name: php7.4-fpm
    state: restarted
