---
- name: Verify role part 1
  hosts: all
  become: no
  tasks:
    - name: Test that providing auth creds to our vhost gives us content.
      command: curl --fail -sSL http://test:test@{{ nginx_server_name }}/molecule-curl-test.php --resolve {{ nginx_server_name }}:80:127.0.0.1
      register: curl_result

    - name: Show results to a human
      debug:
        var: curl_result

    - name: Assert that curl_result contains the expected content
      assert:
        that:
          - '"It works!" in curl_result.stdout'

    - name: Test that using the OPTIONS header bypasses basic http auth.
      command: curl --fail -sSL -XOPTIONS http://{{ nginx_server_name }}/molecule-curl-test.php --resolve {{ nginx_server_name }}:80:127.0.0.1
      register: curl_options_result

    - name: Debug curl_options_result
      debug:
        var: curl_options_result

    - name: Make curl_options_result assertions
      assert:
        that:
          - curl_options_result.stdout == ''

    - name: Test that skipping creds and OPTIONS denies access to content.
      command: curl --fail -sSLI http://{{ nginx_server_name }}/molecule-curl-test.php --resolve {{ nginx_server_name }}:80:127.0.0.1
      register: curl_unauth_result
      ignore_errors: true

    - name: Debug curl_unauth_result
      debug:
        var: curl_unauth_result

    - name: Make curl_unauth_result assertions
      assert:
        that:
          - curl_unauth_result.failed
          - '"401 Unauthorized" in curl_unauth_result.stdout or "401 Unauthorized" in curl_unauth_result.stderr'

    - name: Make sure our x-foo header was present in the response.
      assert:
        that:
          - '"x-molecule-foo: headers-are-fun" in curl_result.stdout'


- name: Verify role part 2 - change PHP version on the vhost to make sure things don't blow up.
  hosts: all
  become: no
  vars:
    php_version: 8.0
  roles:
    - role: ansible-role-virtual-host
