#!/bin/bash
set -eu
set -o pipefail

source /usr/local/lib/acro/bash/functions.sh

## Ansible helper script to support nginx_aliases being optional.
## This would end up being way too convoluted to try and accomplish inside the playbook.

function main () {

  CMD="/usr/local/bin/certbot-auto"
  CMD="$CMD certonly"
  CMD="$CMD --no-self-upgrade"
  CMD="$CMD --non-interactive"
  CMD="$CMD --webroot"
  CMD="$CMD --webroot-path /var/www/letsencrypt"
  CMD="$CMD --agree-tos"
  CMD="$CMD --email webmaster@acromedia.com"
  CMD="$CMD --cert-name ${NGINX_PRIMAL_NAME}"
  CMD="$CMD --keep"
  CMD="$CMD --domains ${DOMAINS_LIST}"
  (set -x && $CMD --dry-run && $CMD)

}

main "$@"
