---
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - 2-nginx_aliases-is-a-lie
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.8
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - geerlingguy/docker-ubuntu2004-ansible:latest
          - geerlingguy/docker-ubuntu1804-ansible:latest
          #- geerlingguy/docker-centos8-ansible:latest   # Can't test this until the PHP role supports CentOS
          #- geerlingguy/docker-centos7-ansible:latest   # Can't test this until the PHP role supports CentOS
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.8
        with:
          image: "${{ matrix.image }}"
          options: parallel
        env:
          MOLECULE_DOCKER_IMAGE: "${{ matrix.image }}"
          max_failures: 1
